### ISSUE TITLE
Yaml not working when wholroyd.jinja extension enabled

### ISSUE THREAD

**Issue by d-enk** [ruschaaf/extended-embedded-languages#1]
![Peek 2023-07-03 15-13](https://github.com/ruschaaf/extended-embedded-languages/assets/43112758/42e1f8a0-c5b3-4343-9e39-21f0e5cfb89e)

**Comment by ruschaaf** [comment]
Thank you for the report (and the helpful animation!). It looks like this is due to the Jinja extension completely overriding the VSCode YAML syntax definition with its own (which then includes the VSCode syntax), rather than the extension adding Jinja templates as an injection. I'll do some tests and see what the options are.

**Comment by ruschaaf** [comment]
Should be fixed by the commit above, and will be included in the next release
