### ISSUE TITLE
ERB/EPP/YAML-in-YAML support?

### ISSUE THREAD

**Issue by claviola** [ruschaaf/extended-embedded-languages#3]
Thanks for the extension, really great idea!

I'm wondering if you'd consider supporting other host languages as well. If so, these would be really nice:

- Ruby/[Embedded Ruby](https://github.com/ruby/erb), the latter being heavily used in Ruby on Rails and [Puppet](https://www.puppet.com/docs/puppet/8/lang_template_erb.html)
- [Embedded Puppet](https://www.puppet.com/docs/puppet/8/lang_template_epp.html#lang_template_epp), which is quite similar in syntax

And last but not least, one that is probably a lot more difficult, so more of a long shot, but who knows...

I'd like to somehow have different syntax highlighting rules within the same language.

Going back to my previous example: Puppet has Hiera, which allows one to separate their data from Puppet code. The docs feature some [examples](https://www.puppet.com/docs/puppet/8/hiera_quick.html#create_test_class), but it's basically YAML/JSON, often times (ab)used to embed almost raw YAML/JSON – which could be properly parsed by other extensions like [logstash editor](https://marketplace.visualstudio.com/items?itemName=fbaligand.vscode-logstash-editor) ([syntax here](https://github.com/randomchance/vscode-logstash-configuration-syntax/blob/master/syntaxes/logstash.tmLanguage)) if it were in its own file, which either gets parsed as generic YAML or as a specific syntax. Since your extension attacks this problem for other host languages, I thought this might be pertinent.

Once again thanks a lot!

**Comment by ruschaaf** [comment]
Thank you for the suggestions! Ruby is definitely a good candidate for the next host language to add.  I'll have to take a look at puppet as well.

For the Embedded Ruby and Embedded Puppet cases could you describe a bit more what you'd expect to see? As I'm thinking about it, these template languages are almost the inverse of the problem I was working on. I.e. you would want to inject a single language's highlighting rules (e.g. Ruby) into a large number of host languages (e.g. html or json or anything else you might be generating). That does sound very useful, but I think it would need to be a different extension since it would be a very different architecture. 

FWIW I just saw a Jinja extension while investigating issue #1 that takes an interesting approach of defining a bunch of sub-languages - e.g. `jinja-html` or `jinja-json` which are presumably simple new language grammars that are just a combination of the two syntax highlighting rules. If they aren't already generating all of those combinations automatically I could definitely see where they could, and then could add support for any number of template languages and embedded languages. But then you could get a combinatorial explosion of choices when selecting which language you want to use in VSCode. (Do you want jinja-html or erb-html or ejs-html ...)

**Comment by claviola** [comment]
Hmm, I think you're right! An ERB/EPP is mostly code in some other language with some templating interspersed throughout.

Could you link to that other extension?

**Comment by ruschaaf** [comment]
Sure - that extension is [Better Jinja](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml) and the grammars are what I mentioned above, just referencing both Jinja and the host language ([example](https://github.com/samuelcolvin/jinjahtml-vscode/blob/main/syntaxes/jinja-json.tmLanguage.json))

**Comment by ruschaaf** [comment]
Just a quick followup - The VSCode ruby grammar already supports several languages. See this file https://github.com/microsoft/vscode/blob/main/extensions/ruby/syntaxes/ruby.tmLanguage.json and search for, e.g. "Heredoc with embedded c++. The built in ruby syntax is something like:
```ruby
<<-CPP
int func(int x, int y) {
  return x+y;
}
CPP
```
